version: "3"

services:
  centos:
    image: isystk/centos8
    build:
      context: ".."
      dockerfile: "./docker/centos/Dockerfile"
      args:
        USER: "isystk"
    volumes:
      - ..:/home/isystk
    tty: true
    stdin_open: true
    privileged: true
    command: /sbin/init
